services:
  jenkins:
    build: ./
    container_name: jenkins-container
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "5000:5000"
    privileged: true
