import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
    //agent { label 'principal' }
    agent any
    environment {
        appName = "variable"
        googleChatWebhook = credentials('google-chat-webhook')
    }
    stages {
        stage("paso 1") {
            steps {
                script {
                    sh "echo 'hola mundo'"
                }
            }
        }
    }
    post {
        always {
            deleteDir()
            sh "echo 'fase always'"
            script {
                def message = "Build ${currentBuild.fullDisplayName} finished with status: ${currentBuild.currentResult}"
                sh """
                    curl -X POST -H 'Content-Type: application/json' \
                    -d '{"text": "${message}"}' \
                    ${googleChatWebhook}
                """
            }
        }
        success {
            sh "echo 'fase success'"
        }
        failure {
            sh "echo 'fase failure'"
        }
    }
}
